# Generated by Django 4.1 on 2022-10-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='تصویر محصول'),
        ),
    ]
