# Generated by Django 4.1 on 2022-10-31 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2022, 10, 31), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
