# Generated by Django 4.1 on 2022-12-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
